Makefile, sfc/Makefile, target-ethos/Makefile, target-libretro/Makefile
Same as what I did in libretro-bsnes, complete with the renaming of the output files.  This change needs to be merged along with the PR for libretro-super which knows about the change.
=> mercury now builds all three profiles without a make clean

target-libretro/Makefile
iOS needs -DIOS in bsnes_mercury's version of libco.  (But not bsnes's)
=> Probably fix iOS builds

Makefile, sfc/Makefile, sfc/alt/cpu/cpu.cpp, sfc/alt/cpu/cpu.hpp, sfc/alt/cpu/serialization.cpp, sfc/alt/cpu/timing.cpp, sfc/cpu/cpu.hpp, sfc/cpu/serialization.cpp, sfc/cpu/timing/irq.cpp, sfc/cpu/timing/timing.cpp, sfc/system/system.cpp, sfc/system/system.hpp
This is a fix that removes one full frame of input lag. There is already a pull request for a similar fix, but that fix was thought to have side effects in certain corner cases (enabling overscan mid-frame). See old pull request here:
https://github.com/libretro/bsnes-mercury/pull/17
This new code relies on the fact that the NMI (non-maskable interrupt) triggers right at the beginning of the VBLANK period. By exiting the emulator loop with a frame event right when the emulator raises NMI, we're able to exit before the input is read, thereby shaving off one frame of input lag.
The neat thing about this version of the fix is that it should work with games that modify the overscan bit mid-frame. Waiting for NMI should be reliable, since this is what game code itself does to detect when a …
=> Trigger frame event on NMI, with trigger on vcounter() == 241 as fallback

sfc/alt/cpu/timing.cpp, sfc/cpu/timing/timing.cpp, sfc/system/system.cpp
_Note: This is copied from the corresponding pull request for the bsnes-libretro core (https://github.com/libretro/bsnes-libretro/pull/19):_
This pull request fixes an issue observed in Alien vs Predator, where the screen would stretch out horizontally seconds after you start moving in the first level. See this thread for details:
http://libretro.com/forums/showthread.php?t=6728
It was observed that the issue only occurred with the lagfix enabled. After analyzing the code it seems this bug was introduced while investigating the MSU-1 issue reported here: #14
It was found that the lagfix didn't cause those MSU-1 issues, but the code changes that were made to the lagfix were kept, since they were considered an improvement. The issue with these code changes appears to be the following:
The …
=> Fix lagfix regression which makes multiple frame events possible within a single VBLANK interval

sfc/alt/cpu/timing.cpp, sfc/cpu/timing/irq.cpp, sfc/cpu/timing/timing.cpp
Moved the clearing of the frame_event_performed flag from sfc/cpu/timing/timing.cpp to sfc/cpu/timing/irq.cpp, so that it occurs at exactly the same place as where the nmi_valid signal goes from high to low. This is only a slight change from previously, where the flag was cleared in scanline() when vcounter()==0. The change may not have any practical effects, but it does make more sense, since the old code actually clears the flag just before the nmi_valid signal goes low.
I've made the corresponding change to sfc/alt/cpu/timing.cpp as well, even though it's actually not needed there (the interrupt code executes inside scanline() without any delay anyway). I made this change just to make sure that the code for the two CPU variants mimic each other as closely as possible (easier to …
=> Change when frame_event_performed flag is cleared

Makefile
Most of the libretro cores check if `DEBUG=1` is set while the bsnes cores check if `debug` is set. This PR will change the bsnes-mercury Makefile to be more like the other cores as being able to set `DEBUG=0` or `DEBUG=1` can be useful.
=> Make setting DEBUG like other libretro cores

target-libretro/Makefile, target-libretro/jni/Android.mk, target-libretro/libretro.cpp
This patch makes this core report the git version along with its library_version. This is important because otherwise it is impossible to replicate a build without extra knowledge, and things like Netplay that demand versions be the same can't be reliably known to work.
=> Report git version with library_version

target-libretro/Makefile, target-libretro/jni/Android.mk
Same idea behind. https://github.com/libretro/bsnes-libretro/pull/28
If `.git` is missing an easy to avoid error is printed.
=> Allow setting GIT_VERSION

sfc/chip/sdd1/sdd1.cpp
This fix is courtesy of @bparker06 .
This fixes https://github.com/libretro/bsnes-mercury/issues/34.
=> SDD1 backport.

sfc/chip/cx4/cx4.cpp, sfc/chip/spc7110/decompressor.cpp
If compiled with `-Wall` this will silence the following `-Wparentheses` warnings.
```
In file included from sfc/chip/spc7110/dcu.cpp:1:0,
from sfc/chip/spc7110/spc7110.cpp:6:
sfc/chip/spc7110/decompressor.cpp: In member function ‘uint32 SuperFamicom::Decompressor::deinterleave(uint64, unsigned int)’:
sfc/chip/spc7110/decompressor.cpp:17:34: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]
data = data & (1ull << bits) - 1;
^
sfc/chip/spc7110/decompressor.cpp: In member function ‘void SuperFamicom::Decompressor::decode()’:
sfc/chip/spc7110/decompressor.cpp:75:32: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]
unsigned history = bit - 1 & output;
^
sfc/chip/spc7110/decompressor.cpp:111:44: warning: suggest parentheses around ‘-’ in operand …
```
=> Silence more -Wparentheses warnings

nall/string/char/compare.hpp
If compiled with `-Wall` this silences a `-Wunused-variable` warning which is spammed.
```
In file included from ./nall/string/char.hpp:4:0,
from ./nall/string.hpp:27,
from ./nall/base64.hpp:5,
from ./emulator/emulator.hpp:22,
from ./processor/processor.hpp:4,
from processor/arm/arm.cpp:1:
./nall/string/char/compare.hpp: In function ‘bool nall::strbegin(const char*, const char*)’:
./nall/string/char/compare.hpp:31:7: warning: unused variable ‘i’ [-Wunused-variable]
int i, ssl = strlen(str), ksl = strlen(key);
^
```
=> Remove unused variable

nall/base64.hpp, nall/png.hpp
Silences another spammed `-Wunused-variable` warning if compiled with `-Wall`.
```
In file included from ./emulator/emulator.hpp:22:0,
from ./sfc/sfc.hpp:4,
from sfc/chip/st0010/st0010.cpp:1:
./nall/base64.hpp: In static member function ‘static nall::vector<unsigned char> nall::Base64::decode(const nall::string&)’:
./nall/base64.hpp:77:11: warning: unused variable ‘buffer’ [-Wunused-variable]
uint8_t buffer, output;
```
=> Remove another unused variable

target-libretro/libretro.cpp
Silences a `-Wreturn-type` warning with `-Wall`.
```
target-libretro/libretro.cpp: In member function ‘virtual uint32_t Callbacks::videoColor(unsigned int, uint16_t, uint16_t, uint16_t, uint16_t)’:
target-libretro/libretro.cpp:382:3: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```
=> Silence a -Wreturn-type warning

target-libretro/libretro.cpp
Silences the following `-Winconsistent-missing-override` warning with clang.
```
target-libretro/libretro.cpp:385:8: warning: 'notify' overrides a member function
but is not marked 'override' [-Winconsistent-missing-override]
void notify(string text) {
^
./emulator/interface.hpp:61:18: note: overridden virtual function is here
virtual void notify(string text) { print(text, "
"); }
^
```
=> Silence a -Winconsistent-missing-override warning

out/.gitignore
I accidentally commited a compiled core to my own fork with the previous PR before removing it with a force push... This will make it so that doesn't happen again.
=> out/.gitignore: Don't accidentally commit compiled cores

target-libretro/libretro.cpp
Hopefully correctly silences the following warning with clang-4.0.0.
```
clang++ -std=gnu++0x -I. -O3 -fomit-frame-pointer -DSFC_LAGFIX -fPIC -D__LIBRETRO__ -DGIT_VERSION=\"" 29a4357"\" -DPROFILE_ACCURACY -c target-libretro/libretro.cpp -o obj/libretro-accuracy.o
target-libretro/libretro.cpp:750:5: warning: array index 6 is past the end of the
array (which contains 6 elements) [-Warray-bounds]
data_str[6]=0;
^        ~
target-libretro/libretro.cpp:738:3: note: array 'data_str' declared here
char addr_str[7], data_str[6];
^
1 warning generated.
```
I tested cheats and they seem to work correctly.
Also see https://github.com/libretro/bsnes-libretro/pull/40.
=> Silence a -Warray-bounds warning with clang

nall/bit.hpp
When compiled with gcc7, the bsnes-accuracy core will enter an infinite loop while compiling this code with `-fstrict-aliasing`.
```
template<unsigned bits> inline uintmax_t uclip(const uintmax_t x) {
enum : uintmax_t { b = 1ull << (bits - 1), m = b * 2 - 1 };
return (x & m);
}
```
This specifically happens with `return x;`.
As a temporary workaround until a proper solution can be found I suggest setting `-fno-strict-aliasing` for this particular code with a `#pragma`. This is further guarded so that it will only be applied for the accuracy profile and gcc newer than 7. I tested this with both gcc and clang where it compiled correctly.
See this issue for more information. https://github.com/libretro/bsnes-mercury/issues/47
=> Workaround for a gcc7 compiler bug

sfc/dsp/dsp.cpp, sfc/system/video.cpp
fixes hang in Magical Drop before game-over screen in endless mode; makes the black-screen garbage less visible. Backported from upstream v102r18; brings this fork in-line with the bsnes-libretro fork.
=> make luma=0 darker and randomize initial DSP register state

libco/aarch64.c
This fixes compile on the buildbot.
=> Not all compiles define lr. Use x30 instead.

Makefile
The libraries are made in `out/` and not `obj/`. I am not sure about `.a` so I left that alone. @Alcaro, can you make sure this is right?
=> Make clean is cleaning the wrong directories.

.travis.yml
This should build all three core profiles for travis. It would helpful in case a regression only affects one of the profiles.
Of course wait till travis actually builds successfully before merging.
=> travis: Build all three core profiles.

nall/bit.hpp
This issue is no longer present with gcc 8.1.1 so disable it there.
Some relevant links.
https://github.com/libretro/bsnes-mercury/issues/47
https://github.com/libretro/bsnes-mercury/pull/50
https://github.com/libretro/bsnes-libretro/pull/57
=> Update gcc7 workaround.

target-libretro/Makefile
Allows installing the core to locations other than /usr/lib on linux.
Also fix macOS and iOS uninstall paths.
=> Allow specifying core installdir

nall/Makefile
This allows cross compilers to be properly used
=> nall: Allow compiler to be overriden

emulator/interface.hpp, sfc/cartridge/markup.cpp, sfc/chip/msu1/msu1.cpp, target-libretro/libretro.cpp
Requires a _romname_.msu file as well as matching pcm files (_romname_-1.pcm etc.), same as newer bsnes/snes9x.
=> Support loading MSU-1 roms without markup (.bml) file
